version: '3'
services:
  mongo:
    image: mongo:4.2
    volumes:
      - 'mongo:/data/db'
    networks:
      - simplognet

  apiserver:
    build: ./simplog
    ports:
      - "8080:8080"
    networks:
      - simplognet
    depends_on:
      - mongo

volumes:
  mongo:

networks:
  simplognet:
