version: '3'
services:
  mongo:
    image: mongo
    networks:
      - simplognet

  apiserver:
    build: ./simplog
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - simplognet

networks:
  simplognet: